#!/bash/sh
#
#if no vehicle name is given
#i.e. -z $1 is defined and it is NULL
#
#if no command line arg

if [ -z $1 ]
then
  rental="*** Unknown vehicle ***"
elif [ -n $1 ]
then 
 # otherwise make first arg as rental
  rental=$1
fi

# case

 case $rental in
    "car") echo "For $rental Rs. 20 per km";;
    "van") echo "For $rental Rs. 10 per km";;
    "jeep") echo "For $rental Rs.15 per km";;
    "car") echo "For $rental Rs. 5 per km";;
    *) echo "Sorry, I can not get a $rental for you";;
esac
 
