#!/bin/sh
#
#Script to see whether a argument is positive or negative or zero
#
if [ $# -eq 0 ]
then
  echo "$0 : You must give one integer"
  exit 1
fi


if test $1 -gt 0
then
  echo "$1 is positive"
elif test $1 -eq 0
then 
 echo "$1 is Neither positive or negative"
else
 echo "$1 is negative"
fi

