#!/bin/sh
#
#Script to print multiplication table of a number
#
if [ $# -eq 0 ]
then
  echo "Error-Number missing in command line argument"
  echo "Use to Print multiplication table of a number"
  echo "Syntax : $0 number"
  exit 4
fi
for i in 1 2 3 4 5 6 7 8 9 10
do
  echo "$1 * $i = `expr $1 \* $i`"
done
