#!/bin/sh
#
#Script to print multiplication number of a number using while loop
#
if [ $# -eq 0 ]
then
  echo "Error : No number entered"
  echo "Syntax: $0 number"
  exit 1
fi
i=1
while [ $i -le 10 ]
do
  echo "$1 * $i = `expr $1 \* $i`"
  i=`expr $i + 1`
done
